# Generated by Django 2.0.4 on 2018-05-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20180501_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
    ]
